blank_issues_enabled: true
contact_links:
  - name: General Discussion
    url: https://github.com/jaakla/semantic-field-types/discussions
    about: For questions, ideas, or general discussion about semantic field types
